{
 "title": "DB Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Nb Tables",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_idx_scan)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb Rows inserted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_ins", "legendFormat": "{{relname}}" }
   ]
  },
  {
   "title": "Nb rows deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_stat_user_tables_n_tup_del", "legendFormat": "{{relname}}" }
   ]
  },
  {
   "title": "Activity Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"recofilm_db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    { "expr": "pg_stat_user_tables_size_bytes", "legendFormat": "{{relname}}" }
   ]
  }
 ]
}